on:
  workflow_dispatch:
name: test 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test buildah paths
        run: |
         buildah login -u ${{ github.repository_owner }} -p ${{ github.token }} ghcr.io
         env
         cat /home/runner/.docker/config.json | jq '.' 
         cat /var/tmp/containers-user-1001/containers/containers/auth.json | jq '.' | sed 's/: ".*/: SNIP/' 

