on:
  workflow_dispatch:
name: test 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test buildah paths
        run: |
         buildah login -u ${{ github.repository_owner }} -p ${{ github.token }} ghcr.io
         env
         find / -name auth.json -or -name config.json
